# Generated by Django 4.1.2 on 2022-10-07 06:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_editpost_header_image_editpost_snippet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('product_snippet', models.CharField(default='Click link above to read...', max_length=255)),
                ('product_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
