# Generated by Django 4.1.2 on 2022-11-22 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theblog.category'),
            preserve_default=False,
        ),
    ]
