# Generated by Django 4.1.2 on 2022-11-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_remove_category2_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theblog.category'),
        ),
    ]
