# Generated by Django 4.1.2 on 2023-01-20 04:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_rename_middle_category_productdata_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('general_name', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('category2', models.CharField(max_length=255)),
                ('sub_categoryOne', models.CharField(max_length=255)),
                ('sub_categoryTwo', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('imgURL1', models.CharField(max_length=255, null=True)),
                ('imgURL2', models.CharField(max_length=255, null=True)),
                ('imgURL3', models.CharField(max_length=255, null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('spec', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('weight', models.IntegerField()),
                ('size_one', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
