# Generated by Django 4.1.2 on 2023-01-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0022_homeproductdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproductdata',
            name='imgURL1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeproductdata',
            name='imgURL2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeproductdata',
            name='imgURL3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
