# Generated by Django 4.1.2 on 2023-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0024_alter_productdata_imgurl1_alter_productdata_imgurl2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproductdata',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
